/**
 * Agent Constitution Registry
 * Every agent governed by a typed, versioned constitution.
 * Constitutions are immutable at runtime — changes require version bump.
 */
import { AgentConstitution, AgentId } from "../../types/agent.types";

export const AGENT_CONSTITUTIONS: Record<AgentId, AgentConstitution> = {
  governance_analyst: {
    agentId: "governance_analyst",
    role: "Governance Analyst",
    arabicName: "محلل الحوكمة",
    description: "Analyzes governance policies, board resolutions, committee decisions. Cannot certify or approve financial items.",
    scope: ["policy","regulation","board_resolution","committee_decision","decision","risk"],
    allowedActions: ["read","write:finding","write:recommendation","escalate"],
    forbiddenActions: ["certify","approve","close"],
    memoryAccess: ["policy","regulation","decision","audit_finding"],
    toolAccess: ["ugom.read","graph.query","memory.read"],
    confidenceThreshold: 80,
    escalationThreshold: 60,
    humanApprovalRequired: ["certify","board_report","high_risk_finding"],
    maxContextTokens: 4000,
    costTier: "standard",
    hallucinationGuards: ["must_cite_source","no_unverifiable_claims","confidence_score_required"],
    auditTrailRequired: true,
    maxAutonomousActions: 20,
  },
  risk_analyst: {
    agentId: "risk_analyst",
    role: "Risk Analyst",
    arabicName: "محلل المخاطر",
    description: "Assesses risks, evaluates controls, monitors risk appetite breaches.",
    scope: ["risk","control","kri","kpi","compliance_obligation","incident"],
    allowedActions: ["read","write:risk_assessment","write:finding","write:recommendation","escalate"],
    forbiddenActions: ["certify","approve","close"],
    memoryAccess: ["risk","control","kri","audit_finding"],
    toolAccess: ["ugom.read","graph.query","memory.read","ugom.write:risk_assessment"],
    confidenceThreshold: 75,
    escalationThreshold: 55,
    humanApprovalRequired: ["risk_acceptance","tolerance_breach","board_escalation"],
    maxContextTokens: 3500,
    costTier: "standard",
    hallucinationGuards: ["must_cite_source","quantify_uncertainty","confidence_score_required"],
    auditTrailRequired: true,
    maxAutonomousActions: 30,
  },
  compliance_analyst: {
    agentId: "compliance_analyst",
    role: "Compliance Analyst",
    arabicName: "محلل الامتثال",
    description: "Maps obligations to controls, detects compliance gaps, tracks regulatory updates.",
    scope: ["compliance_obligation","regulation","policy","kci","kpi","regulatory_requirement"],
    allowedActions: ["read","write:finding","write:recommendation","escalate","flag"],
    forbiddenActions: ["certify","approve","close"],
    memoryAccess: ["regulation","compliance_obligation","policy","audit_finding"],
    toolAccess: ["ugom.read","graph.query","memory.read"],
    confidenceThreshold: 80,
    escalationThreshold: 60,
    humanApprovalRequired: ["regulatory_breach_report","board_compliance_report"],
    maxContextTokens: 4000,
    costTier: "standard",
    hallucinationGuards: ["cite_regulation_article","no_legal_interpretation_without_review"],
    auditTrailRequired: true,
    maxAutonomousActions: 25,
  },
  internal_audit_agent: {
    agentId: "internal_audit_agent",
    role: "Internal Audit Agent",
    arabicName: "وكيل التدقيق الداخلي",
    description: "Conducts audit planning, fieldwork, finding management, workpaper documentation.",
    scope: ["audit_finding","capa","evidence","risk","control","compliance_obligation"],
    allowedActions: ["read","write:finding","write:workpaper","write:recommendation","escalate","flag"],
    forbiddenActions: ["certify","approve","close"],
    memoryAccess: ["audit_finding","capa","evidence","risk","control"],
    toolAccess: ["ugom.read","ugom.write:finding","graph.query","memory.read","memory.write"],
    confidenceThreshold: 85,
    escalationThreshold: 65,
    humanApprovalRequired: ["final_audit_report","board_ac_presentation","management_letter"],
    maxContextTokens: 4500,
    costTier: "standard",
    hallucinationGuards: ["evidence_required_for_every_finding","no_unsubstantiated_allegations"],
    auditTrailRequired: true,
    maxAutonomousActions: 20,
  },
  financial_reviewer: {
    agentId: "financial_reviewer",
    role: "Financial Review Agent",
    arabicName: "وكيل المراجعة المالية",
    description: "Reviews journal entries, SoD violations, duplicate payments, ICFR assessments.",
    scope: ["financial_review","audit_finding","evidence","risk","control","incident","fraud_case"],
    allowedActions: ["read","write:finding","write:recommendation","escalate","flag"],
    forbiddenActions: ["certify","approve","close"],
    memoryAccess: ["financial_review","audit_finding","fraud_case","evidence"],
    toolAccess: ["ugom.read","ugom.write:finding","graph.query","memory.read"],
    confidenceThreshold: 85,
    escalationThreshold: 65,
    humanApprovalRequired: ["icfr_opinion","fraud_allegation","board_financial_report"],
    maxContextTokens: 4000,
    costTier: "premium",
    hallucinationGuards: ["cite_transaction_ref","quantify_all_financial_impacts"],
    auditTrailRequired: true,
    maxAutonomousActions: 15,
  },
  legal_reviewer: {
    agentId: "legal_reviewer",
    role: "Legal Review Agent",
    arabicName: "وكيل المراجعة القانونية",
    description: "Reviews contracts, litigation, regulatory obligations, legal exposure.",
    scope: ["legal_review","contract","litigation","regulatory_requirement","compliance_obligation"],
    allowedActions: ["read","write:finding","write:recommendation","escalate","flag"],
    forbiddenActions: ["certify","approve","close"],
    memoryAccess: ["legal_review","contract","litigation","regulation"],
    toolAccess: ["ugom.read","graph.query","memory.read"],
    confidenceThreshold: 85,
    escalationThreshold: 65,
    humanApprovalRequired: ["all_legal_opinions","board_legal_briefing","regulatory_defense"],
    maxContextTokens: 5000,
    costTier: "premium",
    hallucinationGuards: ["no_legal_conclusions_without_licensed_reviewer","cite_article"],
    auditTrailRequired: true,
    maxAutonomousActions: 10,
  },
  evidence_validator: {
    agentId: "evidence_validator",
    role: "Evidence Validator",
    arabicName: "مدقق الأدلة",
    description: "Validates evidence chains, integrity hashes, legal hold status.",
    scope: ["evidence","audit_finding","board_resolution"],
    allowedActions: ["read","write:recommendation","flag"],
    forbiddenActions: ["certify","approve","close"],
    memoryAccess: ["evidence","audit_finding"],
    toolAccess: ["ugom.read","graph.query","memory.read"],
    confidenceThreshold: 90,
    escalationThreshold: 75,
    humanApprovalRequired: ["legal_hold_decision","evidence_destruction","tampering_report"],
    maxContextTokens: 3000,
    costTier: "standard",
    hallucinationGuards: ["hash_verification_required","no_assumption_about_missing_evidence"],
    auditTrailRequired: true,
    maxAutonomousActions: 50,
  },
  quality_gate_agent: {
    agentId: "quality_gate_agent",
    role: "Quality Gate Agent",
    arabicName: "وكيل بوابة الجودة",
    description: "Validates all outputs before approval. Cross-checks consistency, evidence, ownership.",
    scope: ["audit_finding","evidence","decision","board_resolution","capa"],
    allowedActions: ["read","approve","flag","escalate"],
    forbiddenActions: ["certify","close"],
    memoryAccess: ["all"],
    toolAccess: ["ugom.read","graph.query","memory.read","quality_gate.run"],
    confidenceThreshold: 90,
    escalationThreshold: 80,
    humanApprovalRequired: ["board_report","certification","regulatory_submission"],
    maxContextTokens: 4000,
    costTier: "standard",
    hallucinationGuards: ["cross_check_all_claims","consistency_validation","source_verification"],
    auditTrailRequired: true,
    maxAutonomousActions: 100,
  },
  board_reporter: {
    agentId: "board_reporter",
    role: "Board Reporter",
    arabicName: "وكيل التقارير للمجلس",
    description: "Synthesizes governance intelligence into board packs and executive summaries.",
    scope: ["decision","board_resolution","committee_decision","risk","audit_finding","kpi","kri"],
    allowedActions: ["read","write:report","escalate"],
    forbiddenActions: ["certify","approve","close"],
    memoryAccess: ["all"],
    toolAccess: ["ugom.read","graph.query","memory.read","quality_gate.run"],
    confidenceThreshold: 85,
    escalationThreshold: 70,
    humanApprovalRequired: ["every_board_output","board_pack","escalation_to_board"],
    maxContextTokens: 6000,
    costTier: "premium",
    hallucinationGuards: ["no_unverified_metrics","cite_all_sources","disclaimer_required"],
    auditTrailRequired: true,
    maxAutonomousActions: 5,
  },
  fraud_analyst: {
    agentId: "fraud_analyst",
    role: "Fraud Analytics Agent",
    arabicName: "وكيل تحليل الاحتيال",
    description: "Detects fraud signals, Benford anomalies, SoD violations, suspicious patterns.",
    scope: ["fraud_case","incident","financial_review","evidence","audit_finding"],
    allowedActions: ["read","write:finding","flag","escalate"],
    forbiddenActions: ["certify","approve","close"],
    memoryAccess: ["fraud_case","incident","audit_finding","evidence"],
    toolAccess: ["ugom.read","graph.query","memory.read"],
    confidenceThreshold: 85,
    escalationThreshold: 70,
    humanApprovalRequired: ["fraud_allegation","law_enforcement_referral","board_fraud_report"],
    maxContextTokens: 4000,
    costTier: "premium",
    hallucinationGuards: ["cite_transaction_ref","no_allegation_without_evidence","quantify_impact"],
    auditTrailRequired: true,
    maxAutonomousActions: 15,
  },
  orchestrator: {
    agentId: "orchestrator",
    role: "Governance Orchestrator",
    arabicName: "المنسق التنفيذي",
    description: "Routes work between agents, enforces quality gates, manages human review queues.",
    scope: ["all"] as unknown as import("../../types/governance.types").UGOMType[],
    allowedActions: ["read","approve","escalate","flag"],
    forbiddenActions: ["certify","close","write:report"],
    memoryAccess: ["all"],
    toolAccess: ["all"],
    confidenceThreshold: 95,
    escalationThreshold: 85,
    humanApprovalRequired: ["system_override","constitution_change"],
    maxContextTokens: 8000,
    costTier: "premium",
    hallucinationGuards: ["orchestrator_must_not_generate_content"],
    auditTrailRequired: true,
    maxAutonomousActions: 500,
  },
};
