/**
 * Event Schema Registry — versioned schemas for all governance events.
 * Every event type has a registered schema with validation rules.
 * Schema evolution is tracked — old versions remain valid for replay.
 */
import { GovernanceEventType } from "../../types/events.v3.types";

export interface EventSchema {
  eventType:    GovernanceEventType;
  version:      string;
  description:  string;
  requiredFields: string[];
  optionalFields: string[];
  payloadShape: Record<string, string>;  // field → type description
  classification: "risk" | "control" | "policy" | "audit" | "agent" | "tenant" | "board";
  sensitivity:  "public" | "internal" | "confidential" | "highly_confidential";
  retentionDays:number;
}

export const EVENT_SCHEMA_REGISTRY: Record<GovernanceEventType, EventSchema> = {
  RiskCreated:           { eventType:"RiskCreated",           version:"1.0", description:"New risk identified", requiredFields:["riskId","code","title","category","inherentScore","toleranceBreached","appetiteBreached","owner"], optionalFields:["linkedControls","linkedRegulations"], payloadShape:{ riskId:"string", code:"string", inherentScore:"number", toleranceBreached:"boolean" }, classification:"risk",    sensitivity:"confidential",        retentionDays:2555 },
  RiskUpdated:           { eventType:"RiskUpdated",           version:"1.0", description:"Risk updated",       requiredFields:["riskId"],                  optionalFields:["previousScore","newScore"],                                                                                   payloadShape:{ riskId:"string" },                                                                   classification:"risk",    sensitivity:"confidential",        retentionDays:2555 },
  RiskApproved:          { eventType:"RiskApproved",          version:"1.0", description:"Risk acceptance approved", requiredFields:["riskId","approvedBy"],  optionalFields:[],                                                                                                          payloadShape:{ riskId:"string", approvedBy:"string" },                                              classification:"risk",    sensitivity:"confidential",        retentionDays:2555 },
  RiskToleranceBreached: { eventType:"RiskToleranceBreached", version:"1.0", description:"Risk exceeds tolerance", requiredFields:["riskId","riskCode","breachType","actualScore","threshold","escalateTo"], optionalFields:[],                                                          payloadShape:{ riskId:"string", actualScore:"number" },                                             classification:"risk",    sensitivity:"highly_confidential", retentionDays:3650 },
  RiskAppetiteBreached:  { eventType:"RiskAppetiteBreached",  version:"1.0", description:"Risk exceeds appetite", requiredFields:["riskId","riskCode","actualScore"],                            optionalFields:[],                                                                       payloadShape:{ riskId:"string", actualScore:"number" },                                             classification:"risk",    sensitivity:"highly_confidential", retentionDays:3650 },
  ControlCreated:        { eventType:"ControlCreated",        version:"1.0", description:"Control created",    requiredFields:["controlId","code"],                                             optionalFields:[],                                                                       payloadShape:{ controlId:"string" },                                                                classification:"control", sensitivity:"internal",            retentionDays:2555 },
  ControlTested:         { eventType:"ControlTested",         version:"1.0", description:"Control test completed", requiredFields:["controlId","testScore","passed"], optionalFields:["findings"],                                                                                       payloadShape:{ controlId:"string", testScore:"number", passed:"boolean" },                          classification:"control", sensitivity:"confidential",        retentionDays:2555 },
  ControlFailed:         { eventType:"ControlFailed",         version:"1.0", description:"Control failed test", requiredFields:["controlId","score","findings","linkedRiskIds"], optionalFields:[],                                                                                      payloadShape:{ controlId:"string", score:"number" },                                                classification:"control", sensitivity:"highly_confidential", retentionDays:3650 },
  ControlDeficiency:     { eventType:"ControlDeficiency",     version:"1.0", description:"Control deficiency", requiredFields:["controlId"],                                                   optionalFields:[],                                                                       payloadShape:{ controlId:"string" },                                                                classification:"control", sensitivity:"highly_confidential", retentionDays:3650 },
  SoDViolationDetected:  { eventType:"SoDViolationDetected",  version:"1.0", description:"SoD violation",      requiredFields:["userId","conflictId","action1","action2","entityId","blocked"], optionalFields:[],                                                                       payloadShape:{ userId:"string", blocked:"boolean" },                                                classification:"control", sensitivity:"highly_confidential", retentionDays:3650 },
  FindingOpened:         { eventType:"FindingOpened",         version:"1.0", description:"Audit finding opened", requiredFields:["findingId","code","severity"],                               optionalFields:[],                                                                       payloadShape:{ findingId:"string", severity:"string" },                                             classification:"audit",   sensitivity:"confidential",        retentionDays:3650 },
  FindingClosed:         { eventType:"FindingClosed",         version:"1.0", description:"Audit finding closed", requiredFields:["findingId","closedBy"],                                      optionalFields:["capaId"],                                                               payloadShape:{ findingId:"string" },                                                                classification:"audit",   sensitivity:"confidential",        retentionDays:3650 },
  FindingEscalated:      { eventType:"FindingEscalated",      version:"1.0", description:"Finding escalated",  requiredFields:["findingId","escalatedTo"],                                     optionalFields:[],                                                                       payloadShape:{ findingId:"string", escalatedTo:"string" },                                          classification:"audit",   sensitivity:"highly_confidential", retentionDays:3650 },
  FindingReopened:       { eventType:"FindingReopened",       version:"1.0", description:"Finding reopened",   requiredFields:["findingId","reason"],                                          optionalFields:[],                                                                       payloadShape:{ findingId:"string" },                                                                classification:"audit",   sensitivity:"confidential",        retentionDays:3650 },
  CAPACreated:           { eventType:"CAPACreated",           version:"1.0", description:"CAPA created",       requiredFields:["capaId","findingId","owner"],                                  optionalFields:[],                                                                       payloadShape:{ capaId:"string" },                                                                   classification:"audit",   sensitivity:"confidential",        retentionDays:2555 },
  CAPAOverdue:           { eventType:"CAPAOverdue",           version:"1.0", description:"CAPA overdue",       requiredFields:["capaId","dueDate","owner"],                                    optionalFields:[],                                                                       payloadShape:{ capaId:"string" },                                                                   classification:"audit",   sensitivity:"confidential",        retentionDays:2555 },
  CAPAClosed:            { eventType:"CAPAClosed",            version:"1.0", description:"CAPA closed",        requiredFields:["capaId","closedBy","capaId"],                                  optionalFields:["retestResult"],                                                         payloadShape:{ capaId:"string" },                                                                   classification:"audit",   sensitivity:"confidential",        retentionDays:2555 },
  PolicyCreated:         { eventType:"PolicyCreated",         version:"1.0", description:"Policy created",     requiredFields:["policyId","code","version"],                                   optionalFields:[],                                                                       payloadShape:{ policyId:"string", version:"string" },                                               classification:"policy",  sensitivity:"internal",            retentionDays:3650 },
  PolicyApproved:        { eventType:"PolicyApproved",        version:"1.0", description:"Policy approved",    requiredFields:["policyId","code","version","approvedBy","effectiveFrom"],      optionalFields:["supersedes"],                                                           payloadShape:{ policyId:"string", approvedBy:"string" },                                            classification:"policy",  sensitivity:"internal",            retentionDays:3650 },
  PolicyRejected:        { eventType:"PolicyRejected",        version:"1.0", description:"Policy rejected",    requiredFields:["policyId","rejectedBy","reason"],                              optionalFields:[],                                                                       payloadShape:{ policyId:"string" },                                                                 classification:"policy",  sensitivity:"confidential",        retentionDays:3650 },
  PolicyExpired:         { eventType:"PolicyExpired",         version:"1.0", description:"Policy expired",     requiredFields:["policyId","code"],                                             optionalFields:[],                                                                       payloadShape:{ policyId:"string" },                                                                 classification:"policy",  sensitivity:"internal",            retentionDays:3650 },
  PolicyConflictDetected:{ eventType:"PolicyConflictDetected",version:"1.0", description:"Policy conflict",    requiredFields:["policyId1","policyId2","reason"],                              optionalFields:[],                                                                       payloadShape:{ policyId1:"string", policyId2:"string" },                                            classification:"policy",  sensitivity:"confidential",        retentionDays:3650 },
  ComplianceViolation:   { eventType:"ComplianceViolation",   version:"1.0", description:"Compliance breach",  requiredFields:["obligationId","regulationId","regulatorName","severity","detectedBy"], optionalFields:["penalty","dueDate"],                                            payloadShape:{ obligationId:"string", severity:"string" },                                          classification:"policy",  sensitivity:"highly_confidential", retentionDays:3650 },
  ObligationDue:         { eventType:"ObligationDue",         version:"1.0", description:"Obligation due",     requiredFields:["obligationId"],                                                optionalFields:[],                                                                       payloadShape:{ obligationId:"string" },                                                             classification:"policy",  sensitivity:"confidential",        retentionDays:2555 },
  ObligationBreach:      { eventType:"ObligationBreach",      version:"1.0", description:"Obligation breached", requiredFields:["obligationId","severity"],                                   optionalFields:[],                                                                       payloadShape:{ obligationId:"string" },                                                             classification:"policy",  sensitivity:"highly_confidential", retentionDays:3650 },
  EvidenceAttached:      { eventType:"EvidenceAttached",      version:"1.0", description:"Evidence attached",  requiredFields:["evidenceId","entityId","entityType"],                          optionalFields:[],                                                                       payloadShape:{ evidenceId:"string" },                                                               classification:"audit",   sensitivity:"confidential",        retentionDays:3650 },
  EvidenceExpired:       { eventType:"EvidenceExpired",       version:"1.0", description:"Evidence expired",   requiredFields:["evidenceId","entityId"],                                       optionalFields:[],                                                                       payloadShape:{ evidenceId:"string" },                                                               classification:"audit",   sensitivity:"internal",            retentionDays:3650 },
  EvidenceTampered:      { eventType:"EvidenceTampered",      version:"1.0", description:"Evidence tampered",  requiredFields:["evidenceId","detectedBy"],                                     optionalFields:[],                                                                       payloadShape:{ evidenceId:"string" },                                                               classification:"audit",   sensitivity:"highly_confidential", retentionDays:3650 },
  LegalHoldApplied:      { eventType:"LegalHoldApplied",      version:"1.0", description:"Legal hold",         requiredFields:["evidenceId","reason","appliedBy"],                             optionalFields:[],                                                                       payloadShape:{ evidenceId:"string" },                                                               classification:"audit",   sensitivity:"highly_confidential", retentionDays:3650 },
  ApprovalRequested:     { eventType:"ApprovalRequested",     version:"1.0", description:"Approval requested", requiredFields:["requestId","entityId","entityType","action","requestedBy"],   optionalFields:[],                                                                       payloadShape:{ requestId:"string" },                                                                classification:"policy",  sensitivity:"confidential",        retentionDays:2555 },
  ApprovalGranted:       { eventType:"ApprovalGranted",       version:"1.0", description:"Approval granted",   requiredFields:["requestId","approvedBy"],                                     optionalFields:["notes"],                                                                payloadShape:{ requestId:"string", approvedBy:"string" },                                           classification:"policy",  sensitivity:"confidential",        retentionDays:3650 },
  ApprovalRejected:      { eventType:"ApprovalRejected",      version:"1.0", description:"Approval rejected",  requiredFields:["requestId","rejectedBy","reason"],                             optionalFields:[],                                                                       payloadShape:{ requestId:"string" },                                                                classification:"policy",  sensitivity:"confidential",        retentionDays:3650 },
  ApprovalEscalated:     { eventType:"ApprovalEscalated",     version:"1.0", description:"Approval escalated", requiredFields:["requestId","escalatedTo"],                                    optionalFields:[],                                                                       payloadShape:{ requestId:"string" },                                                                classification:"policy",  sensitivity:"confidential",        retentionDays:3650 },
  ApprovalExpired:       { eventType:"ApprovalExpired",       version:"1.0", description:"Approval SLA expired", requiredFields:["requestId","slaDeadline"],                                  optionalFields:[],                                                                       payloadShape:{ requestId:"string" },                                                                classification:"policy",  sensitivity:"confidential",        retentionDays:2555 },
  AgentTaskQueued:       { eventType:"AgentTaskQueued",       version:"1.0", description:"Agent task queued",  requiredFields:["agentId","taskId","action"],                                   optionalFields:["entityId"],                                                             payloadShape:{ agentId:"string", taskId:"string" },                                                 classification:"agent",   sensitivity:"internal",            retentionDays:365  },
  AgentTaskCompleted:    { eventType:"AgentTaskCompleted",    version:"1.0", description:"Agent task done",    requiredFields:["agentId","taskId","action","entityId","confidenceScore","requiresHumanReview","outputId"], optionalFields:[],                                          payloadShape:{ agentId:"string", confidenceScore:"number" },                                        classification:"agent",   sensitivity:"internal",            retentionDays:730  },
  AgentTaskFailed:       { eventType:"AgentTaskFailed",       version:"1.0", description:"Agent task failed",  requiredFields:["agentId","taskId","error"],                                    optionalFields:[],                                                                       payloadShape:{ agentId:"string", error:"string" },                                                  classification:"agent",   sensitivity:"internal",            retentionDays:730  },
  AgentOutputPending:    { eventType:"AgentOutputPending",    version:"1.0", description:"Agent output pending", requiredFields:["outputId","agentId"],                                       optionalFields:[],                                                                       payloadShape:{ outputId:"string" },                                                                 classification:"agent",   sensitivity:"internal",            retentionDays:365  },
  AgentOutputApproved:   { eventType:"AgentOutputApproved",   version:"1.0", description:"Agent output approved", requiredFields:["outputId","approvedBy"],                                  optionalFields:[],                                                                       payloadShape:{ outputId:"string" },                                                                 classification:"agent",   sensitivity:"internal",            retentionDays:730  },
  AgentConstitutionViolation: { eventType:"AgentConstitutionViolation", version:"1.0", description:"Agent violated constitution", requiredFields:["agentId","violation","action"], optionalFields:[],                                                                                    payloadShape:{ agentId:"string", violation:"string" },                                              classification:"agent",   sensitivity:"highly_confidential", retentionDays:3650 },
  BoardDecisionCreated:  { eventType:"BoardDecisionCreated",  version:"1.0", description:"Board decision",     requiredFields:["decisionId","decisionType","decidedBy","decisionBody"],       optionalFields:[],                                                                       payloadShape:{ decisionId:"string" },                                                               classification:"board",   sensitivity:"highly_confidential", retentionDays:3650 },
  BoardActionOverdue:    { eventType:"BoardActionOverdue",    version:"1.0", description:"Board action overdue", requiredFields:["actionId","dueDate"],                                       optionalFields:[],                                                                       payloadShape:{ actionId:"string" },                                                                 classification:"board",   sensitivity:"confidential",        retentionDays:3650 },
  EscalationToBoard:     { eventType:"EscalationToBoard",     version:"1.0", description:"Escalated to board", requiredFields:["entityId","entityType","reason","escalatedBy"],               optionalFields:[],                                                                       payloadShape:{ entityId:"string", reason:"string" },                                                classification:"board",   sensitivity:"highly_confidential", retentionDays:3650 },
  TenantCreated:         { eventType:"TenantCreated",         version:"1.0", description:"Tenant created",     requiredFields:["tenantId","name","plan"],                                     optionalFields:[],                                                                       payloadShape:{ tenantId:"string" },                                                                 classification:"tenant",  sensitivity:"internal",            retentionDays:3650 },
  TenantSuspended:       { eventType:"TenantSuspended",       version:"1.0", description:"Tenant suspended",   requiredFields:["tenantId","reason","suspendedBy"],                             optionalFields:[],                                                                       payloadShape:{ tenantId:"string" },                                                                 classification:"tenant",  sensitivity:"highly_confidential", retentionDays:3650 },
  CrossTenantViolation:  { eventType:"CrossTenantViolation",  version:"1.0", description:"Cross-tenant access attempt", requiredFields:["sourceActorId","sourceTenantId","targetTenantId","attemptedAction","blocked"], optionalFields:["entityId"],                                  payloadShape:{ sourceTenantId:"string", blocked:"boolean" },                                        classification:"tenant",  sensitivity:"highly_confidential", retentionDays:3650 },
  AuditPlanCreated:      { eventType:"AuditPlanCreated",      version:"1.0", description:"Audit plan created", requiredFields:["planId"],                                                     optionalFields:[],                                                                       payloadShape:{ planId:"string" },                                                                   classification:"audit",   sensitivity:"confidential",        retentionDays:3650 },
  AuditEngagementOpened: { eventType:"AuditEngagementOpened", version:"1.0", description:"Audit engagement",   requiredFields:["engagementId"],                                               optionalFields:[],                                                                       payloadShape:{ engagementId:"string" },                                                             classification:"audit",   sensitivity:"confidential",        retentionDays:3650 },
  AuditReportIssued:     { eventType:"AuditReportIssued",     version:"1.0", description:"Audit report issued", requiredFields:["reportId","issuedBy"],                                      optionalFields:[],                                                                       payloadShape:{ reportId:"string" },                                                                 classification:"audit",   sensitivity:"confidential",        retentionDays:3650 },
};

export function getEventSchema(type: GovernanceEventType): EventSchema {
  return EVENT_SCHEMA_REGISTRY[type];
}

export function getSchemasByClassification(cls: EventSchema["classification"]): EventSchema[] {
  return Object.values(EVENT_SCHEMA_REGISTRY).filter(s => s.classification === cls);
}

export function getEventRetentionDays(type: GovernanceEventType): number {
  return EVENT_SCHEMA_REGISTRY[type]?.retentionDays ?? 365;
}
