/**
 * Control Library — universal control taxonomy mapped across all frameworks.
 * Each control is typed with framework mappings, evidence requirements,
 * risk linkages, and maturity indicators.
 */
import { FrameworkId, FrameworkControl } from "../frameworks/framework.types";

// Canonical control IDs (internal SGIP control language)
export type ControlCategory =
  | "access_control"      | "asset_management"     | "audit_logging"
  | "change_management"   | "business_continuity"  | "cryptography"
  | "data_classification" | "incident_response"    | "network_security"
  | "physical_security"   | "policy_management"    | "risk_assessment"
  | "segregation_of_duties"| "supplier_management" | "training_awareness"
  | "vulnerability_management" | "governance_oversight" | "financial_controls"
  | "privacy_controls"    | "identity_management"  | "configuration_management";

export interface CanonicalControl {
  id:              string;   // CTRL-ACC-001
  category:        ControlCategory;
  title:           string;
  description:     string;
  objective:       string;
  type:            "preventive" | "detective" | "corrective" | "directive" | "compensating";
  mode:            "automated" | "manual" | "semi_automated";
  testFrequency:   "continuous" | "daily" | "weekly" | "monthly" | "quarterly" | "annual";
  evidenceTypes:   string[];
  frameworkRefs:   FrameworkControlRef[];
  riskCategories:  string[];
  maturityLevel:   1 | 2 | 3 | 4 | 5;
  implementationEffort: "low" | "medium" | "high" | "very_high";
  automationPotential:  "high" | "medium" | "low" | "not_applicable";
}

export interface FrameworkControlRef {
  frameworkId:  FrameworkId;
  controlCode:  string;
  controlTitle: string;
  mappingType:  "direct" | "partial" | "related";
}

export const CANONICAL_CONTROL_LIBRARY: CanonicalControl[] = [
  // Access Control
  { id:"CTRL-ACC-001", category:"access_control",     title:"User Access Management",          description:"Controls for provisioning and deprovisioning user access",                          objective:"Ensure only authorized users have access to systems and data",                      type:"preventive",  mode:"semi_automated", testFrequency:"quarterly", evidenceTypes:["access_review_report","provisioning_log","role_assignment_record"],         frameworkRefs:[{frameworkId:"ISO_27001",controlCode:"A.9.2",controlTitle:"User access management",mappingType:"direct"},{frameworkId:"NIST_CSF",controlCode:"PR.AC-1",controlTitle:"Identities and credentials",mappingType:"direct"},{frameworkId:"SAMA_CSF",controlCode:"3.3.1",controlTitle:"Access control",mappingType:"direct"}],        riskCategories:["cyber","operational","fraud"],   maturityLevel:2, implementationEffort:"medium", automationPotential:"high"     },
  { id:"CTRL-ACC-002", category:"access_control",     title:"Privileged Access Management",    description:"Controls for managing privileged and administrative accounts",                      objective:"Prevent unauthorized use of privileged accounts",                                   type:"preventive",  mode:"automated",      testFrequency:"monthly",    evidenceTypes:["pam_audit_log","privileged_account_review","just_in_time_access_log"],        frameworkRefs:[{frameworkId:"ISO_27001",controlCode:"A.9.2.3",controlTitle:"Management of privileged access",mappingType:"direct"},{frameworkId:"PCI_DSS",controlCode:"7.2.1",controlTitle:"Access control systems",mappingType:"direct"}],                                                                                                        riskCategories:["cyber","fraud"],                 maturityLevel:3, implementationEffort:"high",   automationPotential:"high"     },
  { id:"CTRL-ACC-003", category:"segregation_of_duties",title:"Segregation of Duties",         description:"Separation of conflicting duties to prevent fraud and errors",                      objective:"No single person can perform conflicting functions",                                 type:"preventive",  mode:"manual",         testFrequency:"annual",     evidenceTypes:["sod_matrix","role_conflict_report","access_review"],                           frameworkRefs:[{frameworkId:"SOX",controlCode:"SOX-404",controlTitle:"Internal control assessment",mappingType:"direct"},{frameworkId:"ISO_27001",controlCode:"A.6.1.2",controlTitle:"Segregation of duties",mappingType:"direct"},{frameworkId:"COBIT_2019",controlCode:"DSS06.03",controlTitle:"Manage roles",mappingType:"direct"}],                riskCategories:["financial","fraud","operational"],maturityLevel:2, implementationEffort:"medium", automationPotential:"medium"   },
  // Risk Management
  { id:"CTRL-RSK-001", category:"risk_assessment",    title:"Enterprise Risk Assessment",      description:"Formal process to identify, analyze, and evaluate organizational risks",             objective:"Maintain comprehensive understanding of risk exposure",                              type:"directive",   mode:"manual",         testFrequency:"quarterly",  evidenceTypes:["risk_register","risk_assessment_report","risk_workshop_minutes"],              frameworkRefs:[{frameworkId:"COSO_ERM",controlCode:"COSO-4",controlTitle:"Risk identification",mappingType:"direct"},{frameworkId:"COBIT_2019",controlCode:"APO12",controlTitle:"Managed risk",mappingType:"direct"},{frameworkId:"ISO_27001",controlCode:"6.1.2",controlTitle:"Information security risk assessment",mappingType:"direct"}],          riskCategories:["all"],                           maturityLevel:2, implementationEffort:"medium", automationPotential:"medium"   },
  { id:"CTRL-RSK-002", category:"risk_assessment",    title:"Risk Appetite & Tolerance",       description:"Board-approved risk appetite statements and tolerance thresholds",                   objective:"Ensure risk-taking aligned with strategic objectives",                               type:"directive",   mode:"manual",         testFrequency:"annual",     evidenceTypes:["board_resolution","risk_appetite_statement","kri_thresholds"],                 frameworkRefs:[{frameworkId:"COSO_ERM",controlCode:"COSO-3",controlTitle:"Risk appetite",mappingType:"direct"},{frameworkId:"CRISC",controlCode:"CRISC-2",controlTitle:"IT risk response",mappingType:"related"}],                                                                                                                                 riskCategories:["strategic","governance"],        maturityLevel:3, implementationEffort:"low",    automationPotential:"low"      },
  // Information Security
  { id:"CTRL-SEC-001", category:"network_security",   title:"Network Segmentation",            description:"Logical segmentation of networks to limit blast radius",                            objective:"Contain breaches and limit lateral movement",                                       type:"preventive",  mode:"automated",      testFrequency:"quarterly",  evidenceTypes:["network_diagram","firewall_rules","segmentation_test_results"],                frameworkRefs:[{frameworkId:"ISO_27001",controlCode:"A.13.1.3",controlTitle:"Segregation in networks",mappingType:"direct"},{frameworkId:"NCA_ECC",controlCode:"3-2",controlTitle:"Network protection",mappingType:"direct"},{frameworkId:"PCI_DSS",controlCode:"1.3.2",controlTitle:"Network access controls",mappingType:"direct"}],             riskCategories:["cyber"],                         maturityLevel:2, implementationEffort:"high",   automationPotential:"medium"   },
  { id:"CTRL-SEC-002", category:"vulnerability_management",title:"Vulnerability Management",   description:"Systematic identification and remediation of security vulnerabilities",             objective:"Reduce attack surface through timely patching and remediation",                     type:"detective",   mode:"semi_automated", testFrequency:"monthly",    evidenceTypes:["vulnerability_scan_report","patch_log","remediation_tracker"],                 frameworkRefs:[{frameworkId:"ISO_27001",controlCode:"A.12.6.1",controlTitle:"Management of technical vulnerabilities",mappingType:"direct"},{frameworkId:"NIST_CSF",controlCode:"DE.CM-8",controlTitle:"Vulnerability scans",mappingType:"direct"},{frameworkId:"SAMA_CSF",controlCode:"3.5.1",controlTitle:"Vulnerability management",mappingType:"direct"}], riskCategories:["cyber","operational"],           maturityLevel:2, implementationEffort:"medium", automationPotential:"high"     },
  { id:"CTRL-SEC-003", category:"cryptography",       title:"Data Encryption at Rest",         description:"Encryption of sensitive data stored in systems and databases",                      objective:"Protect data confidentiality if storage media is compromised",                      type:"preventive",  mode:"automated",      testFrequency:"annual",     evidenceTypes:["encryption_certificate","key_management_policy","db_encryption_config"],        frameworkRefs:[{frameworkId:"ISO_27001",controlCode:"A.10.1.1",controlTitle:"Policy on the use of cryptographic controls",mappingType:"direct"},{frameworkId:"PCI_DSS",controlCode:"3.5.1",controlTitle:"Encrypt stored PAN",mappingType:"direct"},{frameworkId:"GDPR",controlCode:"Art.32",controlTitle:"Security of processing",mappingType:"direct"}],   riskCategories:["cyber","privacy"],               maturityLevel:2, implementationEffort:"medium", automationPotential:"high"     },
  // Privacy
  { id:"CTRL-PRV-001", category:"privacy_controls",   title:"Personal Data Inventory",         description:"Maintained registry of all personal data processed by the organization",            objective:"Understand and control personal data flows",                                        type:"directive",   mode:"semi_automated", testFrequency:"annual",     evidenceTypes:["data_inventory","privacy_notice","consent_records","processing_register"],      frameworkRefs:[{frameworkId:"GDPR",controlCode:"Art.30",controlTitle:"Records of processing activities",mappingType:"direct"},{frameworkId:"ISO_27701",controlCode:"7.2.1",controlTitle:"Organization",mappingType:"direct"},{frameworkId:"ISMS_PDPL",controlCode:"PDPL-9",controlTitle:"Data subject rights",mappingType:"related"}],                  riskCategories:["privacy","regulatory","reputation"],maturityLevel:2,implementationEffort:"medium",automationPotential:"medium"   },
  { id:"CTRL-PRV-002", category:"privacy_controls",   title:"Consent Management",              description:"Mechanisms to obtain, record, and manage data subject consent",                     objective:"Ensure lawful basis for personal data processing",                                   type:"preventive",  mode:"semi_automated", testFrequency:"monthly",    evidenceTypes:["consent_database","consent_withdrawal_log","privacy_notice_version"],           frameworkRefs:[{frameworkId:"GDPR",controlCode:"Art.7",controlTitle:"Conditions for consent",mappingType:"direct"},{frameworkId:"ISMS_PDPL",controlCode:"PDPL-6",controlTitle:"Processing personal data",mappingType:"direct"}],                                                                                                                      riskCategories:["privacy","regulatory"],          maturityLevel:3, implementationEffort:"medium", automationPotential:"high"     },
  // Governance
  { id:"CTRL-GOV-001", category:"governance_oversight",title:"Board Risk Oversight",           description:"Board-level committee for risk governance and oversight",                           objective:"Ensure adequate board-level risk governance",                                        type:"directive",   mode:"manual",         testFrequency:"quarterly",  evidenceTypes:["board_minutes","committee_charter","board_risk_report"],                        frameworkRefs:[{frameworkId:"COBIT_2019",controlCode:"EDM03",controlTitle:"Ensured risk optimization",mappingType:"direct"},{frameworkId:"SOX",controlCode:"SOX-301",controlTitle:"Audit committee responsibilities",mappingType:"related"},{frameworkId:"COSO_ERM",controlCode:"COSO-2",controlTitle:"Governance structure",mappingType:"direct"}],       riskCategories:["governance","strategic"],        maturityLevel:3, implementationEffort:"low",    automationPotential:"low"      },
  { id:"CTRL-GOV-002", category:"policy_management",  title:"Policy Lifecycle Management",     description:"Formal process for creating, approving, reviewing, and retiring policies",          objective:"Ensure policies are current, approved, and aligned with regulatory requirements",    type:"directive",   mode:"manual",         testFrequency:"annual",     evidenceTypes:["policy_register","approval_records","review_evidence","distribution_log"],      frameworkRefs:[{frameworkId:"ISO_27001",controlCode:"A.5.1.1",controlTitle:"Policies for information security",mappingType:"direct"},{frameworkId:"COBIT_2019",controlCode:"APO01.03",controlTitle:"Maintain enabling policies",mappingType:"direct"}],                                                                                                  riskCategories:["governance","compliance"],       maturityLevel:2, implementationEffort:"low",    automationPotential:"medium"   },
  // Business Continuity
  { id:"CTRL-BCM-001", category:"business_continuity","title":"Business Continuity Planning",  description:"Plans and procedures for maintaining operations during disruptions",                 objective:"Ensure organization can continue critical functions during incidents",                type:"corrective",  mode:"manual",         testFrequency:"annual",     evidenceTypes:["bcp_document","bcp_test_report","recovery_time_objectives","crisis_plan"],      frameworkRefs:[{frameworkId:"ISO_22301",controlCode:"8.4.1",controlTitle:"Business continuity plans",mappingType:"direct"},{frameworkId:"NCA_ECC",controlCode:"2-7",controlTitle:"Cybersecurity resilience",mappingType:"related"},{frameworkId:"COBIT_2019",controlCode:"DSS04",controlTitle:"Managed continuity",mappingType:"direct"}],               riskCategories:["operational","strategic"],       maturityLevel:2, implementationEffort:"high",   automationPotential:"low"      },
  // Financial Controls
  { id:"CTRL-FIN-001", category:"financial_controls", title:"Financial Reporting Controls",    description:"Internal controls over financial reporting (ICFR)",                                  objective:"Ensure accuracy and completeness of financial statements",                          type:"detective",   mode:"manual",         testFrequency:"quarterly",  evidenceTypes:["gl_reconciliation","journal_entry_review","management_representation","icfr_report"],frameworkRefs:[{frameworkId:"SOX",controlCode:"SOX-302",controlTitle:"Corporate responsibility",mappingType:"direct"},{frameworkId:"COSO_ERM",controlCode:"COSO-IC",controlTitle:"Internal control",mappingType:"direct"}],                                                                                                                     riskCategories:["financial","fraud","governance"],maturityLevel:3, implementationEffort:"high",   automationPotential:"medium"   },
  { id:"CTRL-FIN-002", category:"audit_logging",      title:"Audit Trail Management",          description:"Comprehensive, immutable audit logging of all significant events",                  objective:"Enable detection, investigation, and reconstruction of security events",            type:"detective",   mode:"automated",      testFrequency:"monthly",    evidenceTypes:["audit_log_sample","log_integrity_report","siem_alerts","log_retention_certificate"],frameworkRefs:[{frameworkId:"ISO_27001",controlCode:"A.12.4.1",controlTitle:"Event logging",mappingType:"direct"},{frameworkId:"PCI_DSS",controlCode:"10.2",controlTitle:"Audit logs",mappingType:"direct"},{frameworkId:"SAMA_CSF",controlCode:"3.8.1",controlTitle:"Logging and monitoring",mappingType:"direct"}],  riskCategories:["cyber","fraud","compliance"],    maturityLevel:2, implementationEffort:"medium", automationPotential:"high"     },
];

export function getControlById(id: string): CanonicalControl | undefined {
  return CANONICAL_CONTROL_LIBRARY.find(c => c.id === id);
}

export function getControlsByCategory(category: ControlCategory): CanonicalControl[] {
  return CANONICAL_CONTROL_LIBRARY.filter(c => c.category === category);
}

export function getControlsByFramework(frameworkId: FrameworkId): CanonicalControl[] {
  return CANONICAL_CONTROL_LIBRARY.filter(c => c.frameworkRefs.some(r => r.frameworkId === frameworkId));
}

export function getControlsByRiskCategory(riskCategory: string): CanonicalControl[] {
  return CANONICAL_CONTROL_LIBRARY.filter(c => c.riskCategories.includes(riskCategory) || c.riskCategories.includes("all"));
}
